version: '3'
services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx.localhost:/etc/nginx/conf.d
      # - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    links:
      - php

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    links:
      - db
    volumes:
      - .:/var/www

  db:
    image: mysql:5.7
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=654321
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=654321
      - MYSQL_DATABASE=dbname
    volumes:
      - "mysql_data:/var/lib/mysql"

  certbot:
     image: certbot/certbot:latest
     command: certonly --dry-run --webroot --webroot-path=/var/www/certbot --email e@mail.com --agree-tos --no-eff-email -d domain.com
     volumes:
       - ./certbot/conf/:/etc/letsencrypt
       - ./certbot/logs/:/var/log/letsencrypt
       - ./certbot/www:/var/www/certbot
     depends_on:
       - nginx

volumes:
  mysql_data: { driver: local }
